version: 2
snapshot:
  widths:
    - 960
    - 1920
  percy-css: |
    .percy-hide,
    .monaco-editor .cursor {
      visibility: hidden !important;
    }
static:
  base-url: /.assets
discovery:
  disable-cache: true
