env:
  ENTERPRISE: '1'
  DOCKER_BUILDKIT: '1'
  FORCE_COLOR: '3'
  GO111MODULE: 'on'
  IMAGE: 'server_instrumented'
  TAG: '${BUILDKITE_BUILD_NUMBER}_${BUILDKITE_RETRY_COUNT}'
  COVERAGE_INSTRUMENT: 'true'
  VAGRANT_RUN_ENV: 'CI'

# set commands to pass until tests are 100% confirmed as working, so as to avoid disruting dev workflow on main
steps:
- artifact_paths: ./*.png;./e2e.mp4;./ffmpeg.log
  command:
    - .buildkite/test.sh sourcegraph-e2e || true
  label: ':docker::arrow_right::chromium:'
  agents:
    queue: 'baremetal'
- command:
    - .buildkite/test.sh sourcegraph-upgrade || true
  timeout_in_minutes: 20
  label: ':docker::arrow-double-up:'
  agents:
    queue: 'baremetal'
