{
 "title": "Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "content": "<div style=\"text-align: left;\">\n  <img src=\"https://sourcegraphstatic.com/sourcegraph-logo-light.png\" style=\"height:30px; margin:0.5rem\"></img>\n  <div style=\"margin-left: 1rem; margin-top: 0.5rem; font-size: 20px;\"><span style=\"color: #8e8e8e\">Overview:</span> High-level insight into the health of Sourcegraph.</span>\n</div>\n<div style=\"display: flex; padding-top: 1rem;\">\n  <div style=\"margin-left: 2rem; margin-right: 2rem;\">\n    <h4><span style=\"color: #8e8e8e\">Critical alerts</span> by service</h4>\n    <p>\n      The number of definitive issues each service has encountered. If this number is ever above 1.0, something is definitively wrong with Sourcegraph and a site admin should investigate.\n      <span style=\"color: #8e8e8e\">Configure paging for this metric.</span>\n      <div style=\"color: #8e8e8e\"><strong>Examples:</strong> Database inaccessible, out of disk space, out of memory.</div>\n    </p>\n  </div>\n  <div style=\"margin-left: 2rem; margin-right: 2rem;\">\n    <h4><span style=\"color: #8e8e8e\">Warning alerts</span> by service</h4>\n    <p>\n      The number of warnings each service has fired. If this number is ever above 1.0, something <em>may be</em> wrong with Sourcegraph and a site admin should take a closer look when convenient.\n      <span style=\"color: #8e8e8e\">Configure email alerting for this metric.</span>\n      <div style=\"color: #8e8e8e\"><strong>Examples:</strong> High latency, high search timeouts.</div>\n    </p>\n  </div>\n</div>"
  },
  {
   "title": "Critical alerts by service",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "open alerts" }
   ],
   "targets": [
    {
     "expr": "sum by (service_name)(max by (level,service_name,name,description)(alert_count{name!=\"\",level=\"critical\"}))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Warning alerts by service",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "open alerts" }
   ],
   "targets": [
    {
     "expr": "sum by (service_name)(max by (level,service_name,name,description)(alert_count{name!=\"\",level=\"warning\"}))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Total alerts defined",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(sum(alert_count{name!=\"\"}) by (level,description))"
    }
   ]
  },
  {
   "title": "Alerts defined",
   "type": "table",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 16 },
   "targets": [
    {
     "expr": "label_replace(sum by (level,description)(max by (level,service_name,name,description)(alert_count{name!=\"\"})), \"_01_level\", \"$1\", \"level\", \"(.*)\")"
    }
   ]
  },
  {
   "title": "Services being monitored",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 19 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(sum(alert_count{name!=\"\"}) by (service_name))"
    }
   ]
  }
 ]
}