groups:
  - name: searcher
    rules:
      - record: alert_count
        labels:
          service_name: searcher
          level: warning
          name: searcher_request_errors
          description: 'searcher: 5+ unindexed search request errors over 5m'
        expr: >-
          clamp_max(clamp_min(floor(
          (sum by (instance)(increase(searcher_service_request_total{code=~"2.."}[5m]))) OR on() vector(0)
          ), 0), 1)
