name: Notify the campaigns team if campaigns are mentioned in the issue
on:
  issues:
    types: [opened]

jobs:
  create_comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-create-comment@v1
        if: contains(github.event.comment.body, 'campaigns')
        with:
          github_token: ${{ secrets.github_token }}
          body: |
            Hey, @team/campaigns! We have been mentioned.
