name: LSIF
on:
  - push
jobs:
  lsif-go:
    if: github.repository == 'sourcegraph/sourcegraph'
    runs-on: ubuntu-latest
    container: sourcegraph/lsif-go
    steps:
      - uses: actions/checkout@v1
      - name: Generate LSIF data
        run: lsif-go
      - name: Upload LSIF data
        run: src lsif upload -github-token=${{ secrets.GITHUB_TOKEN }}

  lsif-typescript:
    if: github.repository == 'sourcegraph/sourcegraph'
    runs-on: ubuntu-latest
    container: sourcegraph/lsif-node
    steps:
      - uses: actions/checkout@v1
      - name: Install build dependencies
        run: apk --no-cache add python g++ make git
      - name: Install dependencies
        run: yarn --ignore-engines --ignore-scripts
      - name: Generate
        run: ./node_modules/.bin/gulp generate
      - name: Generate LSIF data
        run: lsif-tsc -p .
      - name: Upload LSIF data
        run: src lsif upload -github-token=${{ secrets.GITHUB_TOKEN }}
