name: Changelog progress broadcaster
on:
  push:
    branches:
      - bl/progress-action

jobs:
  sync-progress-channel:
    runs-on: ubuntu-latest
    name: Sync changelog to progress channel
    env:
      WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_PROGRESS_CHANNEL }}
      DIFF_PATH: . # CHANGELOG.md | set to . to test
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - run: echo Hello world
        shell: bash
      - run: git diff HEAD^..HEAD -- $DIFF_PATH
        shell: bash
      - run: export COMMIT=HEAD; git diff $COMMIT~1..$COMMIT $DIFF_PATH | python -c 'import json,sys; print(json.dumps(sys.stdin.read()))' > /tmp/diff.json
        shell: bash
      - run: |
          if [ -z "$(cat /tmp/diff.json)" ]; then
            echo "Diff was empty, not posting to Slack";
          else
            echo "Posting diff to #progress channel in Slack";
            curl -XPOST $WEBHOOK_URL -d "{ \"text\": $(cat /tmp/diff.json) }";
          fi
        shell: bash
# - run: echo $WEBHOOK_URL -d '{ "text": "hello world" }'
#   shell: bash
# - run: curl -XPOST "$WEBHOOK_URL" -d "{ \"text\": `cat /tmp/diff.json` }"
#   shell: bash
