name: Changelog progress broadcaster
on:
  push:
    branches:
      - main
      - master

jobs:
  sync-progress-channel:
    runs-on: ubuntu-latest
    name: Sync changelog to progress channel
    env:
      WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_PROGRESS_CHANNEL }}
      DIFF_PATH: CHANGELOG.md  # when testing and you want this to fire on any diff, set this to .
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - run: export COMMIT=HEAD; git diff $COMMIT~1..$COMMIT $DIFF_PATH | python -c 'import json,sys; print(json.dumps(sys.stdin.read()))' > /tmp/diff.json
        shell: bash
      - run: |
          if [ -z "$(cat /tmp/diff.json)" ]; then
            echo "Diff was empty, not posting to Slack";
          else
            echo "Posting diff to #progress channel in Slack";
            curl -XPOST $WEBHOOK_URL -d "{ \"text\": $(cat /tmp/diff.json) }";
          fi
        shell: bash
