name: reviewdog
on: [pull_request]
jobs:
  golangci-lint:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: List files
        run: ls -laht
      - name: golangci-lint
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        uses: docker://reviewdog/action-golangci-lint:latest
